# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fede8b5ed32cb11e6aab16ba8aa2279fbca86f026f13e9993c44d5a7fa38b0c795f99953df2038548c465592cbac223e28053ff0984702c6352ef22848e200b

test:
  secret_key_base: f25be66bdaf658534435ba0ec88ff008e31fd65ce36690dbf805b2e12933d34b7e7992afdc00da5d2ca4b113b94288001d89575f3c018a382f654cb57ec1d6cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
